django_basic/pythonweb/moviepoll/urls.py
from django.urls import path
from . import views

app_name = 'moviepoll'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django_basic/pythonweb/pythonweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('moviepoll/', include('moviepoll.urls')),
]

django_basic/pythonweb/moviepoll/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    content = models.CharField(max_length=300, default='Content in writting.')
    def __str__(self):
        return self.question_text
    

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    choice_poster_link = models.CharField(max_length=200, default='Not available')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django_basic/pythonweb/moviepoll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'moviepoll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()
                                      ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'moviepoll/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'moviepoll/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'moviepoll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('moviepoll:results', args=(question.id,)))

django_basic/pythonweb/moviepoll/templates/moviepoll/detail.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'moviepoll/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Major+Mono+Display" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
</head>

<header class="top">
    <a  href="{% url 'moviepoll:index' %}" class="top-a">Black Friday Movie</a>
    <div class="search-bar"><input type="text" placeholder="Find Polls, Movies, and more..."></div>
    <a href="#" class="fa fa-facebook"></a>
    <a href="#" class="fa fa-twitter"></a>
    <a href="#" class="fa fa-google"></a>
    <a href="#" class="fa fa-linkedin"></a>
</header>


<body>
    <h1 class="poll-topic">{{ question.question_text }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'moviepoll:vote' question.id %}" method="post" class="option-board">
        {% csrf_token %}
        <div>
            <div class="inline_ls">
                <h5 class="option-instruct">Vote the movie you wish to see</h5>
                {% for choice in question.choice_set.all %}
                    <div class="option">
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                    </div>
                {% endfor %}
            </div>
            <div class="inline_album">
                {% for choice in question.choice_set.all %}
                    <figure class="mini_item">
                        <img src="{{ choice.choice_poster_link }}" class="mini_poster"/>
                        <figcaption class="mini_caption">{{ choice.choice_text }}</figcaption>
                    </figure>
                {% endfor %}
            </div>
        </div>
        <br>
        <input type="submit" value="Vote" class="form-submit-button">
    </form>
</body>

django_basic/pythonweb/moviepoll/templates/moviepoll/index.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'moviepoll/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Major+Mono+Display" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
</head>

<header class="top">
    <a  href="{% url 'moviepoll:index' %}" class="top-a">Black Friday Movie</a>
    <div class="search-bar"><input type="text" placeholder="Find Polls, Movies, and more..."></div>
    <a href="#" class="fa fa-facebook"></a>
    <a href="#" class="fa fa-twitter"></a>
    <a href="#" class="fa fa-google"></a>
    <a href="#" class="fa fa-linkedin"></a>
</header>


<body>
{% if latest_question_list %}
    <div>
    {% for question in latest_question_list %}
        <div class="poll">
            <p>
                <a href="{% url 'moviepoll:detail' question.id %}" class="poll-topic">
                    {{ question.question_text }}
                </a>
            </p>
            <p class="poll-content">
                {{ question.content }}
            </p>
            <div>
            {% for choice in question.choice_set.all %}
                <figure class="item">
                    <a href="#"><img src="{{ choice.choice_poster_link }}" class="poster"/></a>
                    <a href="#" class="caption"><figcaption>{{ choice.choice_text }}</figcaption></a>
                </figure>
            {% endfor %}
            </div>
            <a href="{% url 'moviepoll:detail' question.id %}" class="form-vote-button">
               Vote Here
            </a>
        </div>
    {% endfor %}
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>

django_basic/pythonweb/moviepoll/templates/moviepoll/results.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'moviepoll/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Major+Mono+Display" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
</head>

<header class="top">
    <a  href="{% url 'moviepoll:index' %}" class="top-a">Black Friday Movie</a>
    <div class="search-bar"><input type="text" placeholder="Find Polls, Movies, and more..."></div>
    <a href="#" class="fa fa-facebook"></a>
    <a href="#" class="fa fa-twitter"></a>
    <a href="#" class="fa fa-google"></a>
    <a href="#" class="fa fa-linkedin"></a>
</header>

<body>
    <h1 class="poll-topic">{{ question.question_text }}</h1>
    <form class="option-board">
        <div class="inline_ls">
            <h5 class="option-instruct">Result</h5> 
            {% for choice in question.choice_set.all %}
            <div class="option">
                <p class="result">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</p>
            </div>
            {% endfor %}
            </div>
        </div>
        <div class="inline_album">
                {% for choice in question.choice_set.all %}
                    <figure class="mini_item">
                        <img src="{{ choice.choice_poster_link }}" class="mini_poster"/>
                        <figcaption class="mini_caption">{{ choice.choice_text }}</figcaption>
                    </figure>
                {% endfor %}
        </div>
    <br>
    <a class="form-submit-button" href="{% url 'moviepoll:detail' question.id %}">Vote again?</a>
    </form>
</body>